### ISSUE TITLE
Issues while importing to Objective-C Project

### ISSUE THREAD

**Issue by unoiatech** [EngrAhsanAli/AAViewAnimator#1]
Is it possible to add this Library to Objective-C Project. I am trying to add with CocoaPods but I am getting a list of errors in AAViewAnimator Library.
Here is a screenshot from my project : 
![screen shot 2017-06-01 at 1 07 52 pm](https://cloud.githubusercontent.com/assets/17777840/26669413/60cd41cc-46cb-11e7-8cfd-a10807b87aca.png)

**Comment by EngrAhsanAli** [comment]
Which Xcode version you are using to compile the project? Please check that it's supports _Swift 3_ or not. Also please check the **Requirements** in readme file. Thanks!
